name: fileghost
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^9.2.2
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
